name: docker-latest

on:
  push:
    branches: [latest]
    tags: ["*"]
  pull_request:
    branches: [latest]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile
        run: |
          apt-get update -y
          apt-get install --no-install-recommends -y fonts-noto-cjk-extra
          xelatex sciscn
          bibtex sciscn
          xelatex sciscn
          xelatex sciscn

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: sciscn.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: sciscn.pdf
