name: docker-latest

on:
  push:
    branches: [latest]
    tags: ["*"]
  pull_request:
    branches: [latest]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          outputs: type=tar,dest=sciscn.tar

      - name: Load image
        run: tar xf sciscn.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: sciscn.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'pull_request' }} && startsWith(github.ref, 'refs/tags/')
        with:
          files: sciscn.pdf
